package CommandLineInterface;

public enum Status {
    LOGIN_PAGE,
    COLLECTIONS_PAGE,
    MAKE_DECK,
    CHANGE_DECK,
    SHOP_PAGE,
    BUY_PAGE,
    SELL_PAGE,
    WALLET_PAGE,
    BUY_PAGE_FROM_COLLECTION,
    PLAY_PAGE_MY_TURN,
    PLAY_PAGE_MY_OPPONENT_TURN
}
